# Generated by Django 6.0.3 on 2026-03-21 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Настроение',
                'verbose_name_plural': 'Настроения',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('links', models.SlugField(blank=True, verbose_name='Ссылки')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='LikedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=True, verbose_name='Лайк')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лайкнутая песня',
                'verbose_name_plural': 'Лайкнутые песни',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('author_users', models.ManyToManyField(related_name='authored_playlists', to=settings.AUTH_USER_MODEL, verbose_name='Авторы')),
                ('liked_users', models.ManyToManyField(blank=True, related_name='liked_playlists', to=settings.AUTH_USER_MODEL, verbose_name='Лайкнувшие')),
            ],
            options={
                'verbose_name': 'Плейлист',
                'verbose_name_plural': 'Плейлисты',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('cover', models.ImageField(upload_to='releases/', verbose_name='Обложка')),
                ('date', models.DateField(verbose_name='Дата выпуска')),
                ('release_type', models.CharField(choices=[('EP', 'ЕР'), ('ALBUM', 'Альбом'), ('SINGLE', 'Сингл')], default='SINGLE', max_length=10, verbose_name='Тип релиза')),
                ('artists', models.ManyToManyField(to='api.artist', verbose_name='Исполнители')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Релиз',
                'verbose_name_plural': 'Релизы',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('listenings', models.IntegerField(verbose_name='Прослушиваний')),
                ('listenings_last_week', models.IntegerField(verbose_name='Прослушиваний за неделю')),
                ('path', models.SlugField(verbose_name='Путь к файлу')),
                ('artists', models.ManyToManyField(to='api.artist', verbose_name='Исполнители')),
                ('genres', models.ManyToManyField(to='api.genre', verbose_name='Жанры')),
                ('moods', models.ManyToManyField(to='api.mood', verbose_name='Настроения')),
                ('playlist', models.ManyToManyField(blank=True, to='api.playlist', verbose_name='Плейлисты')),
                ('release', models.ManyToManyField(to='api.release', verbose_name='Релизы')),
                ('users', models.ManyToManyField(blank=True, through='api.LikedSong', to=settings.AUTH_USER_MODEL, verbose_name='Лайкнувшие пользователи')),
            ],
            options={
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
            },
        ),
        migrations.AddField(
            model_name='likedsong',
            name='songs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.song', verbose_name='Песня'),
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Время прослушивания')),
                ('songs', models.ManyToManyField(to='api.song', verbose_name='Песни')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'История прослушиваний',
                'verbose_name_plural': 'Истории прослушиваний',
            },
        ),
        migrations.CreateModel(
            name='UserSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст запроса')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Поисковый запрос',
                'verbose_name_plural': 'Поисковые запросы',
            },
        ),
        migrations.AlterUniqueTogether(
            name='likedsong',
            unique_together={('songs', 'user')},
        ),
        migrations.CreateModel(
            name='SongPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playlist', verbose_name='Плейлист')),
                ('songs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.song', verbose_name='Песня')),
            ],
            options={
                'verbose_name': 'Порядок в плейлисте',
                'verbose_name_plural': 'Порядок в плейлисте',
                'unique_together': {('songs', 'playlist')},
            },
        ),
        migrations.CreateModel(
            name='SongRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.release', verbose_name='Релиз')),
                ('songs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.song', verbose_name='Песня')),
            ],
            options={
                'verbose_name': 'Порядок в релизе',
                'verbose_name_plural': 'Порядок в релизе',
                'unique_together': {('songs', 'release')},
            },
        ),
    ]
