# Generated by Django 6.0.3 on 2026-03-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrelease',
            name='disc_order',
            field=models.IntegerField(blank=True, default=1, verbose_name='Порядок в диске'),
            preserve_default=False,
        ),
    ]
