# Generated by Django 6.0.3 on 2026-03-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_songrelease_disc_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='cover',
            field=models.ImageField(default=1, upload_to='artists/', verbose_name='Фото артиста'),
            preserve_default=False,
        ),
    ]
