# Generated by Django 6.0.3 on 2026-03-24 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_artist_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='artists/', verbose_name='Фото артиста')),
            ],
        ),
        migrations.RemoveField(
            model_name='artist',
            name='cover',
        ),
        migrations.AddField(
            model_name='artist',
            name='covers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.cover', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
