# Generated by Django 6.0.3 on 2026-03-27 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cover_remove_artist_cover_artist_covers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=True, verbose_name='Лайк')),
                ('artists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.artist', verbose_name='Артист')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лайкнутый артист',
                'verbose_name_plural': 'Лайкнутые артисты',
                'unique_together': {('artists', 'user')},
            },
        ),
    ]
