# Generated by Django 6.0.3 on 2026-03-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_likedartist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='covers',
        ),
        migrations.AddField(
            model_name='artist',
            name='covers',
            field=models.ManyToManyField(to='api.cover', verbose_name='Фото'),
        ),
    ]
