# Generated by Django 6.0.3 on 2026-03-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_artist_covers_artist_covers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='covers',
        ),
        migrations.AddField(
            model_name='cover',
            name='artists',
            field=models.ManyToManyField(to='api.artist', verbose_name='Артисты'),
        ),
    ]
