# Generated by Django 6.0.3 on 2026-03-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_artist_covers_cover_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cover',
            name='artists',
        ),
        migrations.AddField(
            model_name='artist',
            name='covers',
            field=models.ManyToManyField(to='api.cover', verbose_name='Релизы'),
        ),
    ]
