# Generated by Django 6.0.3 on 2026-03-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_cover_artists_artist_covers'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='disk',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер диска'),
        ),
        migrations.AddField(
            model_name='song',
            name='position',
            field=models.IntegerField(blank=True, null=True, verbose_name='Позиция на диске'),
        ),
    ]
