# Generated by Django 6.0.3 on 2026-03-31 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_song_disk_song_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='release_type',
            new_name='type',
        ),
        migrations.CreateModel(
            name='LikedRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=True, verbose_name='Лайк')),
                ('releases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.release', verbose_name='Релиз')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лайкнутый релиз',
                'verbose_name_plural': 'Лайкнутые релизы',
                'unique_together': {('releases', 'user')},
            },
        ),
    ]
