# Generated by Django 6.0.3 on 2026-04-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_release_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='covers',
            field=models.ManyToManyField(blank=True, to='api.cover', verbose_name='Релизы'),
        ),
    ]
