# Generated by Django 6.0.3 on 2026-04-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_artist_covers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='disk',
            field=models.IntegerField(blank=True, default=1, verbose_name='Номер диска'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='position',
            field=models.IntegerField(blank=True, default=1, verbose_name='Позиция на диске'),
            preserve_default=False,
        ),
    ]
