# Generated by Django 6.0.3 on 2026-04-02 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_song_disk_alter_song_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songrelease',
            name='disc_order',
        ),
    ]
